apiVersion: v1
kind: Service
metadata:
  name: two
  labels:
    app: two
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: 8080
  selector:
    app: two
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: two
  labels:
    app: two
spec:
  replicas: 2
  selector:
    matchLabels:
      app: two
  template:
    metadata:
      labels:
        app: two
    spec:
      containers:
        - name: two
          image: n3a1/two:0.1.0
          ports:
          - containerPort: 8080