apiVersion: v1
kind: Service
metadata:
  name: one
  labels:
    app: one
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: 8080
  selector:
    app: one
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: one
  labels:
    app: one
spec:
  replicas: 2
  selector:
    matchLabels:
      app: one
  template:
    metadata:
      labels:
        app: one
    spec:
      containers:
        - name: one
          image: n3a1/one:0.1.0
          ports:
          - containerPort: 8080